
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module cinnabon_fpga(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// SMA //////////
	input 		          		SMA_CLKIN,
	output		          		SMA_CLKOUT,

	//////////// LED (High Active) //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY (Active Low) //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 (Low Active) //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// LCD //////////
	inout 		     [7:0]		LCD_DATA,
	output		          		LCD_EN,
	output		          		LCD_ON,
	output		          		LCD_RS,
	output		          		LCD_RW,

	//////////// SDCARD //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DAT,
	input 		          		SD_WP_N,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [31:0]		DRAM_DQ,
	output		     [3:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// SSRAM //////////
	output		          		SSRAM_ADSC_N,
	output		          		SSRAM_ADSP_N,
	output		          		SSRAM_ADV_N,
	output		     [3:0]		SSRAM_BE,
	output		          		SSRAM_CLK,
	output		          		SSRAM_GW_N,
	output		          		SSRAM_OE_N,
	output		          		SSRAM_WE_N,
	output		          		SSRAM0_CE_N,
	output		          		SSRAM1_CE_N,

	//////////// Flash //////////
	output		          		FL_CE_N,
	output		          		FL_OE_N,
	output		          		FL_RESET_N,
	input 		          		FL_RY,
	output		          		FL_WE_N,
	output		          		FL_WP_N,

	//////////// Data and Address bus shared by Flash & SSRAM //////////
	output		    [26:1]		FS_ADDR,
	inout 		    [31:0]		FS_DQ,

	//////////// PCIe //////////
	input 		          		PCIE_PERST_N,
	input 		          		PCIE_REFCLK_P,
	input 		     [0:0]		PCIE_RX_P,
	output		     [0:0]		PCIE_TX_P,
	output		          		PCIE_WAKE_N,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO,

	//////////// HSMC, HSMC connect to ADA - High Speed ADC/DAC //////////
	output		          		HSMC_ADA_SCL,
	inout 		          		HSMC_ADA_SDA,
	output		          		HSMC_ADC_CLK_A,
	output		          		HSMC_ADC_CLK_B,
	input 		    [13:0]		HSMC_ADC_DA,
	input 		    [13:0]		HSMC_ADC_DB,
	output		          		HSMC_ADC_OEB_A,
	output		          		HSMC_ADC_OEB_B,
	input 		          		HSMC_ADC_OTR_A,
	input 		          		HSMC_ADC_OTR_B,
	output		          		HSMC_DAC_CLK_A,
	output		          		HSMC_DAC_CLK_B,
	output		    [13:0]		HSMC_DAC_DA,
	output		    [13:0]		HSMC_DAC_DB,
	output		          		HSMC_DAC_MODE,
	output		          		HSMC_DAC_WRT_A,
	output		          		HSMC_DAC_WRT_B,
	input 		          		HSMC_OSC_SMA_ADC4,
	input 		          		HSMC_SMA_DAC4,

	//////////// Fan Control //////////
	inout 		          		FAN_CTRL
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
reg rst;

wire    CLK_65, CLK_125;


wire    g = 0;
wire    v = 1;

wire    ovalid;

wire    [13:0]	sin10_out;
wire    [13:0]	sin_out;
wire    [13:0]	comb;
wire    [31:0]	phasinc1;
wire    [31:0]	phasinc2;

assign  phasinc1 = {g,g,g,g,v,v,g,g,v,v,g,g,v,v,g,g,v,v,g,g,v,v,g,g,v,v,g,g,v,v,g,v};
assign  phasinc2 = {g,v,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g,g};

	nco u0k (
		.clk         (CLOCK_50),         // clk.clk
		.reset_n     (1),     // rst.reset_n
		.clken       (1),       //  in.clken
		.phi_inc_i   (phasinc1),   //    .phi_inc_i
		.freq_mod_i  (),  //    .freq_mod_i
		.phase_mod_i (), //    .phase_mod_i
		.fsin_o      (sin_out),      // out.fsin_o
		.fcos_o      (),      //    .fcos_o
		.out_valid   (ovalid)    //    .out_valid
	);
add	add_inst (
	.dataa ( sin_out ),
	.datab ( sin_out ),
	.result ( comb )
	);

wire reset_n;
assign reset_n = 1'b1;
	
	

wire[63:0] rw_data;
wire[13:0] rw_address;
wire[7:0] rw_byteen;
wire rw_wbit;

wire[15:0] ppw;

assign ppw = {2'b0, rw_address[13:0]};

ramwriter rw0(
  .i_clk			(CLOCK_50),
  .o_data		(rw_data),
  .o_address	(rw_address),
  .o_byteen		(rw_byteen),
  .o_wbit		(rw_wbit)
);
	
  
  cinnabon_fpga_qsys u0 (
        .clk_clk                                    (CLOCK_50),                                    //                        clk.clk
        .reset_reset_n                              (reset_n),                              //                      reset.reset_n
        .pcie_ip_refclk_export                      (PCIE_REFCLK_P),                      //             pcie_ip_refclk.export
        .pcie_ip_pcie_rstn_export                   (PCIE_PERST_N),                   //          pcie_ip_pcie_rstn.export
        .pcie_ip_rx_in_rx_datain_0                  (PCIE_RX_P[0]),                  //              pcie_ip_rx_in.rx_datain_0
        .pcie_ip_tx_out_tx_dataout_0                (PCIE_TX_P[0]),                //             pcie_ip_tx_out.tx_dataout_0
        .onchip_memory_s2_address                       (rw_address),                       //               onchip_memory2_0_s2.address
        .onchip_memory_s2_chipselect                    (1),                    //                                  .chipselect
        .onchip_memory_s2_clken                         (1),                         //                                  .clken
        .onchip_memory_s2_write                         (rw_wbit),                         //                                  .write
        .onchip_memory_s2_readdata                      (),                      //                                  .readdata
        .onchip_memory_s2_writedata                     (rw_data),    
		  .onchip_memory_s2_byteenable                    (rw_byteen),
		  .pio_0_external_connection_export           (ppw)
		  
		  );


//=======================================================
//  Structural coding
//=======================================================


  assign PCIE_WAKE_N = 1'b1;	 // pull-high to avoid system reboot after power off

  
	//////////// FAN Control //////////
assign FAN_CTRL = 1'bz; // turn on FAN
wire hb_50;
assign LEDR[0] = hb_50;
heart_beat	heart_beat_clk50(
	.clk(CLOCK_50),
	.led(hb_50)
);
endmodule

module heart_beat(
	clk,
	led
);

parameter DUR_BITS = 26;

input  clk;
output led;


reg [(DUR_BITS-1):0] cnt;
always @ (posedge clk)
begin
	cnt <= cnt + 1;
end

assign led = cnt[DUR_BITS-1];

endmodule

